apiVersion: v2
name: wg-sockd-ui
description: A Helm chart for deploying wg-sockd UI proxy in Kubernetes
type: application
version: 0.26.0
appVersion: "0.26.0"
maintainers:
  - name: Aleks Dolotin
    url: https://github.com/aleks-dolotin/wg-sockd
keywords:
  - wireguard
  - vpn
  - management
home: https://github.com/aleks-dolotin/wg-sockd

